// Generated by gencpp from file mini/StatusResponse.msg
// DO NOT EDIT!


#ifndef MINI_MESSAGE_STATUSRESPONSE_H
#define MINI_MESSAGE_STATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mini
{
template <class ContainerAllocator>
struct StatusResponse_
{
  typedef StatusResponse_<ContainerAllocator> Type;

  StatusResponse_()
    : status_string()  {
    }
  StatusResponse_(const ContainerAllocator& _alloc)
    : status_string(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_string_type;
  _status_string_type status_string;





  typedef boost::shared_ptr< ::mini::StatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mini::StatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StatusResponse_

typedef ::mini::StatusResponse_<std::allocator<void> > StatusResponse;

typedef boost::shared_ptr< ::mini::StatusResponse > StatusResponsePtr;
typedef boost::shared_ptr< ::mini::StatusResponse const> StatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mini::StatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mini::StatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mini::StatusResponse_<ContainerAllocator1> & lhs, const ::mini::StatusResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status_string == rhs.status_string;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mini::StatusResponse_<ContainerAllocator1> & lhs, const ::mini::StatusResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mini

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mini::StatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mini::StatusResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mini::StatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mini::StatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mini::StatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mini::StatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mini::StatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c41b913733274581895abeeed69a701";
  }

  static const char* value(const ::mini::StatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c41b91373327458ULL;
  static const uint64_t static_value2 = 0x1895abeeed69a701ULL;
};

template<class ContainerAllocator>
struct DataType< ::mini::StatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mini/StatusResponse";
  }

  static const char* value(const ::mini::StatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mini::StatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# response\n"
"string status_string\n"
;
  }

  static const char* value(const ::mini::StatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mini::StatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status_string);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mini::StatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mini::StatusResponse_<ContainerAllocator>& v)
  {
    s << indent << "status_string: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status_string);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MINI_MESSAGE_STATUSRESPONSE_H
